language: go

go:
  - "1.10.x"
  - "1.11.x"

go_import_path: github.com/apache/rocketmq-client-go

env:
  global:
    - NAME_SERVER_ADDRESS=127.0.0.1:9876
    - BROKER_ADDRESS=127.0.0.1:10911
    - TOPIC=test
    - GROUP=testGroup
  matrix:
  - OS_TYPE=centos OS_VERSION=7

before_install:
  - cd ${TRAVIS_HOME}
  - wget https://opensource-rocketmq-client-us.oss-us-west-1.aliyuncs.com/cpp-client/linux/1.2.4/RHEL7.x/librocketmq.tar.gz
  - tar -xzf librocketmq.tar.gz
  - sudo cp librocketmq.so librocketmq.a /usr/local/lib/
  - sudo cp -r rocketmq /usr/local/include/
  - cd ${GOPATH}/src/github.com/apache/rocketmq-client-go

script:
  - export LD_LIBRARY_PATH=/usr/local/lib
  - cd ${GOPATH}/src/github.com/apache/rocketmq-client-go
  - go test ./core
